data <- read.table('household_power_consumption.txt', header=F, sep=';', na.strings='?', skip=66637, nrows=2880)
x <- c(1:2880)
png("plot3.png", width=480, height=480)
plot(x, data$V7, type='l', ylab="Energy sub metering", xlab="", xaxt="n")
lines(x, data$V8, type='l', col='red', ylab="", xlab="", xaxt="n")
lines(x, data$V9, type='l', col='blue', ylab="", xlab="", xaxt="n")
axis(1, at=c(1,1440,2880), labels=c('Thu','Fri','Sat'))
legend('topright', c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lty=c(1,1,1), col=c('black','red','blue'))
dev.off()