data <- read.table('household_power_consumption.txt', header=F, sep=';', na.strings='?', skip=66637, nrows=2880)
x <- c(1:2880)
png("plot4.png", width=480, height=480)
par(mfrow=c(2,2))
plot(x, data$V3, type='l', ylab="Global Active Power (kilowatts)", xlab="", xaxt="n")
axis(1, at=c(1,1440,2880), labels=c('Thu','Fri','Sat'))
plot(x, data$V5, type='l', ylab="Voltage", xlab="datetime", xaxt="n")
axis(1, at=c(1,1440,2880), labels=c('Thu','Fri','Sat'))
plot(x, data$V7, type='l', ylab="Energy sub metering", xlab="", xaxt="n")
lines(x, data$V8, type='l', col='red', ylab="", xlab="", xaxt="n")
lines(x, data$V9, type='l', col='blue', ylab="", xlab="", xaxt="n")
axis(1, at=c(1,1440,2880), labels=c('Thu','Fri','Sat'))
legend('topright', c('Sub_metering_1','Sub_metering_2','Sub_metering_3'), lty=c(1,1,1), col=c('black','red','blue'))
plot(x, data$V4, type='l', ylab="Global reactive power", xlab="datetime", xaxt="n")
axis(1, at=c(1,1440,2880), labels=c('Thu','Fri','Sat'))
dev.off()